// ERRORS
export const EMPTY_ERRORS = "EMPTY_ERRORS";
export const GET_ERRORS = "GET_ERRORS";

// USERS
export const BEFORE_USER = "BEFORE_USER";
export const SET_USER = "SET_USER";
export const SIGNUP_USER = "SIGNUP_USER";
export const LOGIN_USER = "LOGIN_USER";
export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
export const VERIFY_USER = "VERIFY_USER";
export const GOOGLE_SOCIAL = "GOOGLE_SOCIAL";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const RESET_PASSWORD = "RESET_PASSWORD";

// AVATAR
export const BEFORE_AVATAR = "BEFORE_AVATAR";
export const GET_AVATARS = "GET_AVATARS";
export const GET_AVATAR = "SET_AVATAR";
export const CREATE_AVATAR = "CREATE_AVATAR";
export const MODAL_AVATAR = "MODAL_AVATAR";
export const VALIDATE_IMAGE = "VALIDATE_IMAGE";
export const DELETE_AVATAR = "DELETE_AVATAR";

// PRESENTER
export const GET_PRESENTERS = "GET_PRESENTERS";
export const BEFORE_PRESETNTER = "BEFORE_PRESENTER";
export const CREATE_PRESENTER = "CREATE_PRESENTER";
export const SELECT_PRESENTER = "SELECT_PRESENTER";
export const DELETE_PRESENTER = "DELETE_PRESENTER";
